version: 0.2

#env:
  #variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"

phases:
  install:
    commands:
      - sudo apt-get update
      - sudo apt-get --assume-yes install chromium-browser
      - npm install -g @angular/cli
      #- rm -rf node_modules
      #- ng add ng-cli-pug-loader
      - npm install
      - npm run postinstall
  #pre_build:
    #commands:
      # - command
      # - command
  build:
    commands:
      - npm run build
      # - command
  post_build:
    commands:
      - aws s3 cp package.json s3://naloxoneexchange-frontend-build-artifacts
      - aws s3 cp ./bin s3://naloxoneexchange-frontend-build-artifacts/bin --recursive
      - aws s3 cp ./config s3://naloxoneexchange-frontend-build-artifacts/config --recursive
      - aws s3 cp ./dist s3://naloxoneexchange-frontend-build-artifacts/dist --recursive
      - aws s3 cp ./node_modules s3://naloxoneexchange-frontend-build-artifacts/node_modules --recursive

artifacts:
    files:
        - bin/*
        - config/*
        - dist/**/*
        # it is not recommended to copy the entire contents of node modules over
        # and is instead recommended you copy only the required modules. E.g.
        # -node_modules/lodash/*
        # -node_modules/moment/*
        # -node_modules/PACKAGE_NAME/*
        - node_modules/**/*
        - package.json
    discard-paths: no

#cache:
  #paths:
    # - paths
